name: Build CAB

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download CabWiz
        run: |
          curl -L -o cabwiz.zip https://github.com/old-tools/cabwiz/releases/download/v1/cabwiz.zip
          tar -xf cabwiz.zip

      - name: Build CAB
        run: |
          ./cabwiz/cabwiz.exe htc_weather.inf

      - name: Upload CAB
        uses: actions/upload-artifact@v4
        with:
          name: htc_weather
          path: "*.CAB"
